---
name: Ansible Test
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  pull_request_target:
    types: [opened, synchronize]

  push:
    branches:
      - main
      - stable-*

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  # Approve protected environment once instead of once per job in the matrix
  approve:
    name: Approve Integration
    runs-on: ubuntu-latest
    environment:
      name: eco-mecm
    steps:
      - run: echo "Deployment approved"

  integration:
    runs-on: [self-hosted]
    needs:
      - approve
    if: always() && needs.approve.result == 'success'
    name: I (Ⓐ${{ matrix.ansible }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        # Add new versions announced in
        # https://github.com/ansible-collections/news-for-maintainers in a timely manner,
        # consider dropping testing against EOL versions and versions you don't support.
        include:
          - ansible: devel
            python: 3.12
          - ansible: stable-2.16
            python: 3.11
          - ansible: stable-2.17
            python: 3.11
          - ansible: stable-2.18
            python: 3.11
          - ansible: stable-2.19
            python: 3.11
    steps:
      - name: Install python
        run: |
          set -euxo pipefail
          if ! command -v python${{ matrix.python }}; then
            sudo dnf install -y \
              python${{ matrix.python }} \
              python${{ matrix.python }}-pip
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run integration tests
        run: |
          python${{ matrix.python }} -m venv .venv
          source .venv/bin/activate
          pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz
          make integration ANSIBLE_COLLECTIONS_PATH="${{ github.workspace }}"
        env:
          ANSIBLE_COLLECTIONS_PATH: "${{ github.workspace }}"
          MECM_HOSTNAME: ${{ secrets.MECM_HOSTNAME }}
          MECM_USERNAME: ${{ secrets.MECM_USERNAME }}
          MECM_PASSWORD: ${{ secrets.MECM_PASSWORD }}

      - name: Clean up
        if: always()
        run: |
          rm -rf ./*

  check: # This job does nothing and is only used for the branch protection
    # or multi-stage CI jobs, like making sure that all tests pass before
    # a publishing job is started.
    if: always()

    needs:
      - integration

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
